//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smdcrmClient.wscrm {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/smdcrmws")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="wsCliente", Namespace="http://schemas.datacontract.org/2004/07/sdmcrmws.data")]
    [System.SerializableAttribute()]
    public partial class wsCliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_11Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_12Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_13Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_14Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_15Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_16Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_17Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_18Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_19Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_20Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_21Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_22Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_23Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_24Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_25Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_26Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_27Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_28Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_29Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_30Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_31Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_32Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_33Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_34Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_35Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_36Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_37Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_38Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_39Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_40Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_41Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_42Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_43Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_44Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_45Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_46Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_47Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_48Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_49Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_50Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_51Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_52Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_53Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_54Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_55Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_56Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_57Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_58Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_59Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_60Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Campo_9Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_1 {
            get {
                return this.Campo_1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_1Field, value) != true)) {
                    this.Campo_1Field = value;
                    this.RaisePropertyChanged("Campo_1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_10 {
            get {
                return this.Campo_10Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_10Field, value) != true)) {
                    this.Campo_10Field = value;
                    this.RaisePropertyChanged("Campo_10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_11 {
            get {
                return this.Campo_11Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_11Field, value) != true)) {
                    this.Campo_11Field = value;
                    this.RaisePropertyChanged("Campo_11");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_12 {
            get {
                return this.Campo_12Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_12Field, value) != true)) {
                    this.Campo_12Field = value;
                    this.RaisePropertyChanged("Campo_12");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_13 {
            get {
                return this.Campo_13Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_13Field, value) != true)) {
                    this.Campo_13Field = value;
                    this.RaisePropertyChanged("Campo_13");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_14 {
            get {
                return this.Campo_14Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_14Field, value) != true)) {
                    this.Campo_14Field = value;
                    this.RaisePropertyChanged("Campo_14");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_15 {
            get {
                return this.Campo_15Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_15Field, value) != true)) {
                    this.Campo_15Field = value;
                    this.RaisePropertyChanged("Campo_15");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_16 {
            get {
                return this.Campo_16Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_16Field, value) != true)) {
                    this.Campo_16Field = value;
                    this.RaisePropertyChanged("Campo_16");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_17 {
            get {
                return this.Campo_17Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_17Field, value) != true)) {
                    this.Campo_17Field = value;
                    this.RaisePropertyChanged("Campo_17");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_18 {
            get {
                return this.Campo_18Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_18Field, value) != true)) {
                    this.Campo_18Field = value;
                    this.RaisePropertyChanged("Campo_18");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_19 {
            get {
                return this.Campo_19Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_19Field, value) != true)) {
                    this.Campo_19Field = value;
                    this.RaisePropertyChanged("Campo_19");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_2 {
            get {
                return this.Campo_2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_2Field, value) != true)) {
                    this.Campo_2Field = value;
                    this.RaisePropertyChanged("Campo_2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_20 {
            get {
                return this.Campo_20Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_20Field, value) != true)) {
                    this.Campo_20Field = value;
                    this.RaisePropertyChanged("Campo_20");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_21 {
            get {
                return this.Campo_21Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_21Field, value) != true)) {
                    this.Campo_21Field = value;
                    this.RaisePropertyChanged("Campo_21");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_22 {
            get {
                return this.Campo_22Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_22Field, value) != true)) {
                    this.Campo_22Field = value;
                    this.RaisePropertyChanged("Campo_22");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_23 {
            get {
                return this.Campo_23Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_23Field, value) != true)) {
                    this.Campo_23Field = value;
                    this.RaisePropertyChanged("Campo_23");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_24 {
            get {
                return this.Campo_24Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_24Field, value) != true)) {
                    this.Campo_24Field = value;
                    this.RaisePropertyChanged("Campo_24");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_25 {
            get {
                return this.Campo_25Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_25Field, value) != true)) {
                    this.Campo_25Field = value;
                    this.RaisePropertyChanged("Campo_25");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_26 {
            get {
                return this.Campo_26Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_26Field, value) != true)) {
                    this.Campo_26Field = value;
                    this.RaisePropertyChanged("Campo_26");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_27 {
            get {
                return this.Campo_27Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_27Field, value) != true)) {
                    this.Campo_27Field = value;
                    this.RaisePropertyChanged("Campo_27");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_28 {
            get {
                return this.Campo_28Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_28Field, value) != true)) {
                    this.Campo_28Field = value;
                    this.RaisePropertyChanged("Campo_28");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_29 {
            get {
                return this.Campo_29Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_29Field, value) != true)) {
                    this.Campo_29Field = value;
                    this.RaisePropertyChanged("Campo_29");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_3 {
            get {
                return this.Campo_3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_3Field, value) != true)) {
                    this.Campo_3Field = value;
                    this.RaisePropertyChanged("Campo_3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_30 {
            get {
                return this.Campo_30Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_30Field, value) != true)) {
                    this.Campo_30Field = value;
                    this.RaisePropertyChanged("Campo_30");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_31 {
            get {
                return this.Campo_31Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_31Field, value) != true)) {
                    this.Campo_31Field = value;
                    this.RaisePropertyChanged("Campo_31");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_32 {
            get {
                return this.Campo_32Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_32Field, value) != true)) {
                    this.Campo_32Field = value;
                    this.RaisePropertyChanged("Campo_32");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_33 {
            get {
                return this.Campo_33Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_33Field, value) != true)) {
                    this.Campo_33Field = value;
                    this.RaisePropertyChanged("Campo_33");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_34 {
            get {
                return this.Campo_34Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_34Field, value) != true)) {
                    this.Campo_34Field = value;
                    this.RaisePropertyChanged("Campo_34");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_35 {
            get {
                return this.Campo_35Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_35Field, value) != true)) {
                    this.Campo_35Field = value;
                    this.RaisePropertyChanged("Campo_35");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_36 {
            get {
                return this.Campo_36Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_36Field, value) != true)) {
                    this.Campo_36Field = value;
                    this.RaisePropertyChanged("Campo_36");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_37 {
            get {
                return this.Campo_37Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_37Field, value) != true)) {
                    this.Campo_37Field = value;
                    this.RaisePropertyChanged("Campo_37");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_38 {
            get {
                return this.Campo_38Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_38Field, value) != true)) {
                    this.Campo_38Field = value;
                    this.RaisePropertyChanged("Campo_38");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_39 {
            get {
                return this.Campo_39Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_39Field, value) != true)) {
                    this.Campo_39Field = value;
                    this.RaisePropertyChanged("Campo_39");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_4 {
            get {
                return this.Campo_4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_4Field, value) != true)) {
                    this.Campo_4Field = value;
                    this.RaisePropertyChanged("Campo_4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_40 {
            get {
                return this.Campo_40Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_40Field, value) != true)) {
                    this.Campo_40Field = value;
                    this.RaisePropertyChanged("Campo_40");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_41 {
            get {
                return this.Campo_41Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_41Field, value) != true)) {
                    this.Campo_41Field = value;
                    this.RaisePropertyChanged("Campo_41");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_42 {
            get {
                return this.Campo_42Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_42Field, value) != true)) {
                    this.Campo_42Field = value;
                    this.RaisePropertyChanged("Campo_42");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_43 {
            get {
                return this.Campo_43Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_43Field, value) != true)) {
                    this.Campo_43Field = value;
                    this.RaisePropertyChanged("Campo_43");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_44 {
            get {
                return this.Campo_44Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_44Field, value) != true)) {
                    this.Campo_44Field = value;
                    this.RaisePropertyChanged("Campo_44");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_45 {
            get {
                return this.Campo_45Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_45Field, value) != true)) {
                    this.Campo_45Field = value;
                    this.RaisePropertyChanged("Campo_45");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_46 {
            get {
                return this.Campo_46Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_46Field, value) != true)) {
                    this.Campo_46Field = value;
                    this.RaisePropertyChanged("Campo_46");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_47 {
            get {
                return this.Campo_47Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_47Field, value) != true)) {
                    this.Campo_47Field = value;
                    this.RaisePropertyChanged("Campo_47");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_48 {
            get {
                return this.Campo_48Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_48Field, value) != true)) {
                    this.Campo_48Field = value;
                    this.RaisePropertyChanged("Campo_48");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_49 {
            get {
                return this.Campo_49Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_49Field, value) != true)) {
                    this.Campo_49Field = value;
                    this.RaisePropertyChanged("Campo_49");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_5 {
            get {
                return this.Campo_5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_5Field, value) != true)) {
                    this.Campo_5Field = value;
                    this.RaisePropertyChanged("Campo_5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_50 {
            get {
                return this.Campo_50Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_50Field, value) != true)) {
                    this.Campo_50Field = value;
                    this.RaisePropertyChanged("Campo_50");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_51 {
            get {
                return this.Campo_51Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_51Field, value) != true)) {
                    this.Campo_51Field = value;
                    this.RaisePropertyChanged("Campo_51");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_52 {
            get {
                return this.Campo_52Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_52Field, value) != true)) {
                    this.Campo_52Field = value;
                    this.RaisePropertyChanged("Campo_52");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_53 {
            get {
                return this.Campo_53Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_53Field, value) != true)) {
                    this.Campo_53Field = value;
                    this.RaisePropertyChanged("Campo_53");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_54 {
            get {
                return this.Campo_54Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_54Field, value) != true)) {
                    this.Campo_54Field = value;
                    this.RaisePropertyChanged("Campo_54");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_55 {
            get {
                return this.Campo_55Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_55Field, value) != true)) {
                    this.Campo_55Field = value;
                    this.RaisePropertyChanged("Campo_55");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_56 {
            get {
                return this.Campo_56Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_56Field, value) != true)) {
                    this.Campo_56Field = value;
                    this.RaisePropertyChanged("Campo_56");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_57 {
            get {
                return this.Campo_57Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_57Field, value) != true)) {
                    this.Campo_57Field = value;
                    this.RaisePropertyChanged("Campo_57");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_58 {
            get {
                return this.Campo_58Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_58Field, value) != true)) {
                    this.Campo_58Field = value;
                    this.RaisePropertyChanged("Campo_58");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_59 {
            get {
                return this.Campo_59Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_59Field, value) != true)) {
                    this.Campo_59Field = value;
                    this.RaisePropertyChanged("Campo_59");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_6 {
            get {
                return this.Campo_6Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_6Field, value) != true)) {
                    this.Campo_6Field = value;
                    this.RaisePropertyChanged("Campo_6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_60 {
            get {
                return this.Campo_60Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_60Field, value) != true)) {
                    this.Campo_60Field = value;
                    this.RaisePropertyChanged("Campo_60");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_7 {
            get {
                return this.Campo_7Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_7Field, value) != true)) {
                    this.Campo_7Field = value;
                    this.RaisePropertyChanged("Campo_7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_8 {
            get {
                return this.Campo_8Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_8Field, value) != true)) {
                    this.Campo_8Field = value;
                    this.RaisePropertyChanged("Campo_8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo_9 {
            get {
                return this.Campo_9Field;
            }
            set {
                if ((object.ReferenceEquals(this.Campo_9Field, value) != true)) {
                    this.Campo_9Field = value;
                    this.RaisePropertyChanged("Campo_9");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="wsControl", Namespace="http://schemas.datacontract.org/2004/07/sdmcrmws.data")]
    [System.SerializableAttribute()]
    public partial class wsControl : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaHoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrigenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaHora {
            get {
                return this.FechaHoraField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaHoraField, value) != true)) {
                    this.FechaHoraField = value;
                    this.RaisePropertyChanged("FechaHora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Origen {
            get {
                return this.OrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.OrigenField, value) != true)) {
                    this.OrigenField = value;
                    this.RaisePropertyChanged("Origen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wscrm.ISmdcrmws")]
    public interface ISmdcrmws {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmdcrmws/GetData", ReplyAction="http://tempuri.org/ISmdcrmws/GetDataResponse")]
        string GetData(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmdcrmws/GetData", ReplyAction="http://tempuri.org/ISmdcrmws/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmdcrmws/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ISmdcrmws/GetDataUsingDataContractResponse")]
        smdcrmClient.wscrm.CompositeType GetDataUsingDataContract(smdcrmClient.wscrm.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmdcrmws/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ISmdcrmws/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<smdcrmClient.wscrm.CompositeType> GetDataUsingDataContractAsync(smdcrmClient.wscrm.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmdcrmws/GetClientesSync", ReplyAction="http://tempuri.org/ISmdcrmws/GetClientesSyncResponse")]
        smdcrmClient.wscrm.wsCliente[] GetClientesSync(string IdEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmdcrmws/GetClientesSync", ReplyAction="http://tempuri.org/ISmdcrmws/GetClientesSyncResponse")]
        System.Threading.Tasks.Task<smdcrmClient.wscrm.wsCliente[]> GetClientesSyncAsync(string IdEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmdcrmws/PutClienteSync", ReplyAction="http://tempuri.org/ISmdcrmws/PutClienteSyncResponse")]
        smdcrmClient.wscrm.wsControl PutClienteSync(System.IO.Stream JSONdataStream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmdcrmws/PutClienteSync", ReplyAction="http://tempuri.org/ISmdcrmws/PutClienteSyncResponse")]
        System.Threading.Tasks.Task<smdcrmClient.wscrm.wsControl> PutClienteSyncAsync(System.IO.Stream JSONdataStream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmdcrmws/PutClientesSync", ReplyAction="http://tempuri.org/ISmdcrmws/PutClientesSyncResponse")]
        smdcrmClient.wscrm.wsControl PutClientesSync(System.IO.Stream JSONdataStream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmdcrmws/PutClientesSync", ReplyAction="http://tempuri.org/ISmdcrmws/PutClientesSyncResponse")]
        System.Threading.Tasks.Task<smdcrmClient.wscrm.wsControl> PutClientesSyncAsync(System.IO.Stream JSONdataStream);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISmdcrmwsChannel : smdcrmClient.wscrm.ISmdcrmws, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmdcrmwsClient : System.ServiceModel.ClientBase<smdcrmClient.wscrm.ISmdcrmws>, smdcrmClient.wscrm.ISmdcrmws {
        
        public SmdcrmwsClient() {
        }
        
        public SmdcrmwsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmdcrmwsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmdcrmwsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmdcrmwsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(string value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(string value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public smdcrmClient.wscrm.CompositeType GetDataUsingDataContract(smdcrmClient.wscrm.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<smdcrmClient.wscrm.CompositeType> GetDataUsingDataContractAsync(smdcrmClient.wscrm.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public smdcrmClient.wscrm.wsCliente[] GetClientesSync(string IdEmpresa) {
            return base.Channel.GetClientesSync(IdEmpresa);
        }
        
        public System.Threading.Tasks.Task<smdcrmClient.wscrm.wsCliente[]> GetClientesSyncAsync(string IdEmpresa) {
            return base.Channel.GetClientesSyncAsync(IdEmpresa);
        }
        
        public smdcrmClient.wscrm.wsControl PutClienteSync(System.IO.Stream JSONdataStream) {
            return base.Channel.PutClienteSync(JSONdataStream);
        }
        
        public System.Threading.Tasks.Task<smdcrmClient.wscrm.wsControl> PutClienteSyncAsync(System.IO.Stream JSONdataStream) {
            return base.Channel.PutClienteSyncAsync(JSONdataStream);
        }
        
        public smdcrmClient.wscrm.wsControl PutClientesSync(System.IO.Stream JSONdataStream) {
            return base.Channel.PutClientesSync(JSONdataStream);
        }
        
        public System.Threading.Tasks.Task<smdcrmClient.wscrm.wsControl> PutClientesSyncAsync(System.IO.Stream JSONdataStream) {
            return base.Channel.PutClientesSyncAsync(JSONdataStream);
        }
    }
}
